services:
    backend:
        build: .
        image: backend:${TAG:-latest}
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend
        depends_on:
            - db
        restart: unless-stopped
        volumes:
            - "./application.yml:/app/application.yml:ro"

    db:
        image: postgres:18-alpine
        environment:
            - POSTGRES_DB=backend
            - POSTGRES_USER=backend
            - POSTGRES_PASSWORD=backend
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres-data:
