services:
    backend:
        image: reg.kybe.xyz/kybe-pub/backend:latest
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: prod
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/backend
        volumes:
            - ./application.yml:/app/application.yml:ro
        depends_on:
            - db
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 20s
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                order: start-first
                failure_action: rollback
            restart_policy:
                condition: on-failure

    db:
        image: postgres:18-alpine
        environment:
            POSTGRES_DB: backend
            POSTGRES_USER: backend
            POSTGRES_PASSWORD: backend
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U backend -d backend"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        deploy:
            restart_policy:
                condition: on-failure

volumes:
    postgres-data: