services:
    db:
        image: postgres:18-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=backend
            - POSTGRES_USER=backend
            - POSTGRES_PASSWORD=backend
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres-data:
