name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Build Docker Image
        run: |
          docker build -t backend:${{ github.sha }} .
          docker tag backend:${{ github.sha }} backend:latest

      - name: Export and compress Docker image
        run: |
          mkdir -p /tmp/docker-images
          docker save backend:latest | gzip > /tmp/docker-images/backend-latest.tar.gz

      - name: Copy image to server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.RUNNER_SSH_KEY }}
          source: "/tmp/docker-images/backend-latest.tar.gz"
          target: "/tmp/"
          strip_components: 2

      - name: Deploy on remote server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.RUNNER_SSH_KEY }}
          script: |
            gunzip -c /tmp/backend-latest.tar.gz | docker load
            
            cd /opt/backend
            docker-compose up -d
            
            docker image prune -f
            rm -f /tmp/backend-latest.tar.gz

      - name: Cleanup
        if: always()
        run: |
          rm -rf /tmp/docker-images
